import { useState } from 'react';
import { ArrowRight, Car, Check, ChevronDown, Clock3, MapPin, Menu, MessageCircle, Phone, ShieldCheck, Star, X, Zap } from 'lucide-react';
import { whatsappUrl } from './utils/whatsapp';

const services=[['Taxi Service in Jabalpur','Local and outstation taxi booking.','🚕'],['Car Rental in Jabalpur','Comfortable cars for every journey.','🚗'],['Local Taxi','Easy travel within Jabalpur.','📍'],['Outstation Taxi','Reliable intercity travel.','🛣️'],['Tourist Taxi','See more of Madhya Pradesh.','📸'],['Airport Taxi','On-time airport pickup and drop.','✈️'],['Railway Station Taxi','Smooth station transfers.','🚉'],['Jabalpur Sightseeing','Explore local landmarks with ease.','🏞️'],['Tempo Traveller Rental','Group travel, made comfortable.','👥']];
const destinations=['Bhedaghat','Dhuandhar Falls','Marble Rocks','Bargi Dam','Madan Mahal Fort','Dumna Nature Reserve','Gwarighat','Chausath Yogini Temple','Rani Durgavati Museum','Kachnar City'];
const mp=['Kanha','Bandhavgarh','Pench','Amarkantak','Pachmarhi','Khajuraho','Bhopal','Indore','Ujjain','Sanchi'];
const cities=['Jabalpur','Katni','Mandla','Damoh','Narsinghpur','Seoni','Umaria','Rewa','Satna','Sagar','Chhindwara','Shahdol','Bhopal','Indore','Nagpur'];
const routes=['Bhedaghat','Katni','Mandla','Kanha','Bandhavgarh','Nagpur','Bhopal','Rewa','Satna','Pachmarhi','Khajuraho'];
const packages=['Jabalpur Local Sightseeing','Bhedaghat & Dhuandhar Falls','Kanha Trip','Bandhavgarh Trip','Amarkantak Trip','Pachmarhi Trip','Khajuraho Trip','MP Family Tour'];
const image=(q:string)=>`https://images.unsplash.com/${q}?auto=format&fit=crop&w=900&q=80`;
function App(){ const [menu,setMenu]=useState(false); const [sent,setSent]=useState(false); const [form,setForm]=useState<Record<string,string>>({}); const update=(e:any)=>setForm({...form,[e.target.name]:e.target.value}); const submit=(e:any)=>{e.preventDefault();setSent(true);window.open(whatsappUrl(form),'_blank')};
return <div><header className="header"><a className="logo" href="#top"><span className="logoMark">✦</span><span><b>JCRT</b><small>SUMIT TRAVELS</small></span></a><nav className={menu?'open':''}>{['Services','Fleet','Routes','Tour Packages','Cities','About','Contact'].map(x=><a href={'#'+x.toLowerCase().replace(/ /g,'-')} onClick={()=>setMenu(false)} key={x}>{x}</a>)}</nav><a className="headerBook" href="#book">Book now <ArrowRight size={16}/></a><button className="menuBtn" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></header>
<section id="top" className="hero"><div className="heroBg"/><div className="heroContent"><div className="eyebrow"><span/>JABALPUR'S TRUSTED TRAVEL PARTNER</div><h1>Journeys that feel<br/><em>effortless.</em></h1><p>Reliable local, sightseeing, airport, railway station and outstation taxi services from Jabalpur, Madhya Pradesh.</p><div className="heroActions"><a className="btn gold" href="#book">Book a taxi <ArrowRight size={17}/></a><a className="btn light" href={whatsappUrl()} target="_blank"><MessageCircle size={17}/> WhatsApp</a></div><div className="trust"><span><ShieldCheck/> Verified service</span><span><Clock3/> On-time pickup</span><span><Star/> 24/7 support</span></div></div><Booking form={form} update={update} submit={submit} sent={sent}/></section>
<main><section className="section intro" id="services"><div className="sectionHead"><div><div className="eyebrow dark"><span/> OUR SERVICES</div><h2>Every trip. <em>Handled beautifully.</em></h2></div><p>From a quick city ride to a week-long MP adventure, travel comfortably with a local team that knows the way.</p></div><div className="serviceGrid">{services.map(([title,desc,icon])=><article className="serviceCard" key={title}><div className="iconBox">{icon}</div><h3>{title}</h3><p>{desc}</p><a href="#book">Explore service <ArrowRight size={15}/></a></article>)}</div></section>
<section className="darkSection" id="fleet"><div className="sectionHead inverse"><div><div className="eyebrow"><span/> OUR FLEET</div><h2>Room for every <em>kind of trip.</em></h2></div><p>Choose the space you need, with clean, comfortable vehicles and dependable drivers.</p></div><div className="fleetGrid">{[['4 Seater','Couples & small families','photo-1549317661-bd32c8ce0db2'],['5 Seater','Families & small groups','photo-1502877338535-766e1452684a'],['7 Seater','Families & groups','photo-1544620347-c4fd4a3d5957'],['Tempo Traveller','9, 12, 15 & 17 seater','photo-1517457373958-b7bdd4587205']].map(([a,b,c])=><article className="fleetCard" key={a}><img src={image(c)}/><div><span>{a}</span><p>{b}</p><a href="#book">Check availability <ArrowRight size={14}/></a></div></article>)}</div></section>
<section className="section" id="routes"><div className="sectionHead"><div><div className="eyebrow dark"><span/> PLAN YOUR ROUTE</div><h2>Go further, <em>simply.</em></h2></div><p>Popular routes from Jabalpur. Tell us where you are going and we will share current availability and fare.</p></div><div className="routeGrid">{routes.map(r=><a className="route" href="#book" key={r}><span>Jabalpur</span><ArrowRight size={15}/><strong>{r}</strong><small>Get current fare</small></a>)}</div></section>
<Gallery title="Explore Jabalpur by Taxi" eyebrow="JABALPUR TOURISM" items={destinations} ids={['photo-1596402184320-417e7178b2cd','photo-1548013146-72479768bada','photo-1500530855697-b586d89ba3ee','photo-1470770841072-f978cf4d019e','photo-1518005020951-eccb494ad742','photo-1501785888041-af3ef285b470','photo-1469474968028-56623f02e42e','photo-1544735716-392fe2489ffa','photo-1533929736458-ca588d08c8be','photo-1500534623283-312aade485b7']}/>
<Gallery dark title="Explore Madhya Pradesh by Taxi" eyebrow="THE HEART OF INDIA" items={mp} ids={['photo-1469474968028-56623f02e42e','photo-1544735716-392fe2489ffa','photo-1500530855697-b586d89ba3ee','photo-1501785888041-af3ef285b470','photo-1470770841072-f978cf4d019e','photo-1518005020951-eccb494ad742','photo-1494526585095-c41746248156','photo-1548013146-72479768bada','photo-1524492412937-b28074a5d7da','photo-1533929736458-ca588d08c8be']}/>
<section className="section cities" id="cities"><div className="eyebrow dark"><span/> CITIES WE SERVE</div><h2>Local knowledge.<br/><em>Wider horizons.</em></h2><div className="cityList">{cities.map(c=><a href="#book" key={c}>{c}<ArrowRight size={14}/></a>)}</div></section>
<section className="packageSection" id="tour-packages"><div className="eyebrow dark"><span/> CURATED GETAWAYS</div><h2>Take the scenic <em>route.</em></h2><div className="packageGrid">{packages.map((p,i)=><article key={p} style={{backgroundImage:`url(${image(['photo-1500534623283-312aade485b7','photo-1548013146-72479768bada','photo-1469474968028-56623f02e42e','photo-1501785888041-af3ef285b470'][i%4])})`}}><div><span>TRIP {String(i+1).padStart(2,'0')}</span><h3>{p}</h3><a href="#book">Get a quote <ArrowRight size={15}/></a></div></article>)}</div></section>
<section className="why"><div className="whyText"><div className="eyebrow"><span/> WHY SUMIT TRAVELS</div><h2>A better way<br/>to <em>move.</em></h2><p>Thoughtful service, transparent communication and a genuine love for this beautiful region. That is what makes every ride feel different.</p><a className="btn gold" href="#book">Start your journey <ArrowRight size={17}/></a></div><div className="points">{[['01','Local expertise','Routes planned by people who know Jabalpur and Madhya Pradesh inside out.'],['02','Reliable by design','Clear communication and dependable pickups, from first call to final stop.'],['03','Made for you','The right vehicle, the right route and the flexibility your journey needs.']].map(([n,t,d])=><div className="point" key={n}><b>{n}</b><div><h3>{t}</h3><p>{d}</p></div><Check/></div>)}</div></section>
<section className="faq section"><div className="eyebrow dark"><span/> GOOD TO KNOW</div><h2>Frequently asked <em>questions.</em></h2>{['How do I book a taxi in Jabalpur?','Do you offer airport and railway station transfers?','Can I book a taxi for an outstation trip?','Which vehicles are available for group travel?'].map(q=><details key={q}><summary>{q}<ChevronDown size={18}/></summary><p>Get in touch through the booking form, phone or WhatsApp. We will confirm availability and share a current fare for your requirements.</p></details>)}</section>
<section className="contact" id="contact"><div><div className="eyebrow"><span/> LET'S GET MOVING</div><h2>Your next journey<br/><em>starts here.</em></h2><p>Tell us a little about your trip. We will take care of the rest.</p></div><a className="btn gold" href="#book">Book your taxi <ArrowRight size={17}/></a></section>
</main><footer><div className="footerTop"><a className="logo" href="#top"><span className="logoMark">✦</span><span><b>JCRT</b><small>SUMIT TRAVELS</small></span></a><p>Reliable local and outstation journeys from Jabalpur, Madhya Pradesh.</p><div><a href="tel:"><Phone size={17}/> Call us</a><a href={whatsappUrl()}><MessageCircle size={17}/> WhatsApp</a></div></div><div className="footerBottom"><span>© 2024 Sumit Travels. Built for better journeys.</span><span>Jabalpur · Madhya Pradesh · India</span></div></footer><div className="mobileBar"><a href="tel:"><Phone/>Call</a><a href={whatsappUrl()}><MessageCircle/>WhatsApp</a><a href="#book"><Car/>Book</a></div></div>}
function Booking({form,update,submit,sent}:{form:Record<string,string>,update:any,submit:any,sent:boolean}){return <div className="booking" id="book"><div className="bookingTitle"><span>PLAN YOUR RIDE</span><h2>Where to next?</h2><p>Share your details and we will get back with availability.</p></div>{sent&&<div className="success">✓ Your enquiry is ready in WhatsApp.</div>}<form onSubmit={submit}><div className="inputRow"><label>Pickup location<input name="Pickup" placeholder="Jabalpur" onChange={update}/></label><label>Drop location<input name="Drop" placeholder="Where are you going?" onChange={update}/></label></div><div className="inputRow"><label>Date<input name="Date" type="date" onChange={update}/></label><label>Trip type<select name="Trip Type" onChange={update}><option>Local</option><option>One Way</option><option>Round Trip</option><option>Airport Transfer</option><option>Outstation</option><option>Group Travel</option></select></label></div><button className="btn gold full">Get fare & availability <ArrowRight size={16}/></button></form></div>}
function Gallery({title,eyebrow,items,ids,dark=false}:{title:string,eyebrow:string,items:string[],ids:string[],dark?:boolean}){return <section className={'gallery '+(dark?'darkSection':'')}><div className="sectionHead inverse"><div><div className="eyebrow"><span/> {eyebrow}</div><h2>{title}</h2></div><a className="textLink" href="#book">Plan your visit <ArrowRight size={15}/></a></div><div className="galleryGrid">{items.map((x,i)=><a href="#book" className="destination" key={x}><img src={image(ids[i])}/><span>{x}</span><ArrowRight size={15}/></a>)}</div></section>}
export default App;